# Generated by Django 6.0.3 on 2026-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=128)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedCustomer',
            fields=[
                ('phone', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('blocked_at', models.DateTimeField()),
                ('customer_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('phone', models.CharField(db_index=True, max_length=255)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=512, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationToken',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('fcm_token', models.TextField()),
                ('role', models.CharField(db_index=True, max_length=32)),
                ('outlet_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('device_type', models.CharField(default='browser', max_length=64)),
                ('device_info', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('outlet_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('customer_phone', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('customer_phone_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('role', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
