import React, { useState, useMemo } from 'react';
import { OfferCard, MenuItem, Category, AdminSession } from '../types';
import { saveOfferToServer, deleteOfferFromServer } from '../services/orderApi';
import { getOfferConditionLabel } from '../offerUtils';

interface AdminOffersProps {
  session: AdminSession;
  offers: OfferCard[];
  menuItems: MenuItem[];
  onRefresh: () => void;
}

export const AdminOffers: React.FC<AdminOffersProps> = ({
  session,
  offers,
  menuItems,
  onRefresh,
}) => {
  const [isAdding, setIsAdding] = useState(false);
  const [loading, setLoading] = useState(false);

  // Form State
  const [offerTitle, setOfferTitle] = useState('');
  const [displayText, setDisplayText] = useState('');
  const [image, setImage] = useState('');
  const [offerPercentage, setOfferPercentage] = useState<string>('');
  const [targetCategory, setTargetCategory] = useState<string>('All');
  const [targetSize, setTargetSize] = useState<string>('All');
  const [additionalItemName, setAdditionalItemName] = useState<string>('');
  const [minimumOrder, setMinimumOrder] = useState<string>('');
  const [isSundayOffer, setIsSundayOffer] = useState(false);

  // Extract unique product images from menu items to offer as choices
  const menuItemImages = useMemo(() => {
    const imagesSet = new Set<string>();
    menuItems.forEach((item) => {
      if (item.image) imagesSet.add(item.image);
    });
    return Array.from(imagesSet);
  }, [menuItems]);

  const handleSelectImage = (imgUrl: string) => {
    setImage(imgUrl);
  };

  const handleSelectBonusItem = (itemId: string) => {
    if (!itemId) {
      setAdditionalItemName('');
      return;
    }
    const item = menuItems.find((m) => m.id === itemId);
    if (item) {
      setAdditionalItemName(item.name);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!offerTitle.trim() || !displayText.trim()) {
      alert('Offer Title and Offer Text are required!');
      return;
    }

    setLoading(true);
    try {
      const offerId = `offer-${Date.now()}`;
      
      // Resolve additional item image if additionalItemName matches any menu item
      let finalAdditionalItemImage = '';
      if (additionalItemName) {
        const matchedItem = menuItems.find(
          (m) => m.name.toLowerCase().trim() === additionalItemName.toLowerCase().trim()
        );
        if (matchedItem && matchedItem.image) {
          finalAdditionalItemImage = matchedItem.image;
        }
      }

      // Default image if none chosen
      const finalImage = image || menuItemImages[0] || '/images/default-offer.jpeg';

      const newOffer: OfferCard = {
        id: offerId,
        enabled: true,
        offerTitle: offerTitle.trim(),
        displayText: displayText.trim(),
        image: finalImage,
        offerPercentage: offerPercentage ? parseFloat(offerPercentage) : undefined,
        condition: '', // Dynamically generated by utils, keep empty
        additionalItem: additionalItemName.trim() || undefined,
        additionalItemImage: finalAdditionalItemImage || undefined,
        notifyCustomers: true,
        targetCategory: targetCategory !== 'All' ? targetCategory : undefined,
        targetSize: targetCategory === 'Pizza' && targetSize !== 'All' ? targetSize : undefined,
        minimumOrder: minimumOrder ? parseFloat(minimumOrder) : undefined,
        isSundayOffer: isSundayOffer,
      };

      await saveOfferToServer(newOffer);
      alert('Promotion added successfully!');
      
      // Reset form
      setOfferTitle('');
      setDisplayText('');
      setImage('');
      setOfferPercentage('');
      setTargetCategory('All');
      setTargetSize('All');
      setAdditionalItemName('');
      setMinimumOrder('');
      setIsSundayOffer(false);
      setIsAdding(false);
      
      onRefresh();
    } catch (err: any) {
      alert(err.message || 'Failed to save offer');
    } finally {
      setLoading(false);
    }
  };

  const handleToggleEnabled = async (offer: OfferCard) => {
    try {
      await saveOfferToServer({
        ...offer,
        enabled: !offer.enabled,
      });
      onRefresh();
    } catch (err: any) {
      alert(err.message || 'Failed to update offer');
    }
  };

  const handleDelete = async (offerId: string) => {
    if (!window.confirm('Are you sure you want to permanently delete this offer?')) {
      return;
    }
    try {
      await deleteOfferFromServer(offerId);
      onRefresh();
    } catch (err: any) {
      alert(err.message || 'Failed to delete offer');
    }
  };

  const isSunday = new Date().getDay() === 0;

  return (
    <section className="relative mx-auto max-w-6xl p-4 animate-fade-in text-white space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-[10px] font-black uppercase tracking-[0.25em] text-red-500">Marketing & Sales</p>
          <h3 className="font-display text-2xl font-bold font-black text-white">Offers & Promotions</h3>
        </div>
        
        {session.role !== 'staff' && (
          <button
            onClick={() => setIsAdding(!isAdding)}
            className="rounded-2xl bg-gradient-premium border border-red-500/20 px-5 py-3 text-[10px] font-black uppercase tracking-widest text-white shadow-lg active:scale-95 transition-all cursor-pointer"
          >
            {isAdding ? 'Cancel' : '+ Create New Offer'}
          </button>
        )}
      </div>

      {/* Add Offer Form Card */}
      {isAdding && (
        <form onSubmit={handleSubmit} className="rounded-[2rem] border border-white/10 bg-slate-950/80 p-6 shadow-2xl space-y-5 animate-slide-up">
          <h4 className="text-lg font-bold text-slate-100 uppercase tracking-wider">Configure New Promotion</h4>
          
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1.5">Offer Title</label>
              <input
                type="text"
                placeholder="e.g. Sunday Dhamaka!"
                value={offerTitle}
                onChange={(e) => setOfferTitle(e.target.value)}
                className="w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 font-semibold text-white outline-none focus:border-red-500"
                required
              />
            </div>

            <div>
              <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1.5">Offer Text / Description</label>
              <input
                type="text"
                placeholder="e.g. Buy 1 Pizza and get a Free Garlic Bread"
                value={displayText}
                onChange={(e) => setDisplayText(e.target.value)}
                className="w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 font-semibold text-white outline-none focus:border-red-500"
                required
              />
            </div>

            <div>
              <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1.5">Discount Percentage (Optional)</label>
              <input
                type="number"
                min="0"
                max="100"
                placeholder="e.g. 15 for 15% discount"
                value={offerPercentage}
                onChange={(e) => setOfferPercentage(e.target.value)}
                className="w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 font-semibold text-white outline-none focus:border-red-500"
              />
            </div>

            <div>
              <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1.5">Minimum Order Value (Optional)</label>
              <input
                type="number"
                min="0"
                placeholder="e.g. 249"
                value={minimumOrder}
                onChange={(e) => setMinimumOrder(e.target.value)}
                className="w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 font-semibold text-white outline-none focus:border-red-500"
              />
            </div>

            <div>
              <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1.5">Applied on Product Category</label>
              <select
                value={targetCategory}
                onChange={(e) => setTargetCategory(e.target.value)}
                className="w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 font-semibold text-white outline-none focus:border-red-500"
              >
                <option value="All">All Categories</option>
                <option value="Pizza">Pizza</option>
                <option value="Burgers">Burgers</option>
                <option value="Fries">Fries</option>
                <option value="Momos">Momos</option>
                <option value="Beverages">Beverages</option>
                <option value="Sides">Side Orders</option>
              </select>
            </div>

            {targetCategory === 'Pizza' && (
              <div>
                <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1.5">Pizza Size Restriction</label>
                <select
                  value={targetSize}
                  onChange={(e) => setTargetSize(e.target.value)}
                  className="w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 font-semibold text-white outline-none focus:border-red-500"
                >
                  <option value="All">All Sizes</option>
                  <option value="Regular">Regular Only</option>
                  <option value="Medium">Medium Only</option>
                  <option value="Large">Large Only</option>
                </select>
              </div>
            )}

            <div>
              <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1.5">Free / Bonus Item (Optional)</label>
              <select
                onChange={(e) => handleSelectBonusItem(e.target.value)}
                className="w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 font-semibold text-white outline-none focus:border-red-500"
              >
                <option value="">No Free Bonus Item</option>
                {menuItems.map((item) => (
                  <option key={item.id} value={item.id}>
                    {item.name}
                  </option>
                ))}
              </select>
            </div>

            <div className="flex items-center space-x-3 pt-6">
              <input
                type="checkbox"
                id="sunday_checkbox"
                checked={isSundayOffer}
                onChange={(e) => setIsSundayOffer(e.target.checked)}
                className="h-5 w-5 rounded border-white/10 bg-slate-900 text-red-650 focus:ring-0 focus:ring-offset-0 cursor-pointer"
              />
              <label htmlFor="sunday_checkbox" className="text-xs font-bold text-slate-300 uppercase tracking-wider cursor-pointer">
                📅 Is Sunday Automated Offer
              </label>
            </div>
          </div>

          {/* Product Image Option Picker */}
          <div>
            <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-2">Select Promotion Banner Image</label>
            <div className="flex flex-wrap gap-2.5 max-h-32 overflow-y-auto p-2 bg-slate-900/60 rounded-2xl border border-white/5">
              {menuItemImages.map((imgUrl, idx) => (
                <button
                  type="button"
                  key={idx}
                  onClick={() => handleSelectImage(imgUrl)}
                  className={`relative h-12 w-12 rounded-xl overflow-hidden border-2 transition-all hover:scale-105 cursor-pointer ${
                    image === imgUrl ? 'border-red-500 shadow-md scale-105' : 'border-white/10'
                  }`}
                >
                  <img src={imgUrl} alt="Choice" className="h-full w-full object-cover" />
                </button>
              ))}
            </div>
            
            <div className="mt-3">
              <input
                type="text"
                placeholder="Or paste custom image URL..."
                value={image}
                onChange={(e) => setImage(e.target.value)}
                className="w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3.5 text-xs text-white outline-none focus:border-red-500"
              />
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-2xl bg-gradient-premium py-4 text-[11px] font-black uppercase tracking-widest text-white shadow-xl hover:scale-[1.01] active:scale-95 transition-transform disabled:opacity-50 cursor-pointer"
          >
            {loading ? 'Saving...' : 'Add Active Promotion'}
          </button>
        </form>
      )}

      {/* Grid of Offers */}
      <div className="grid gap-5 md:grid-cols-2">
        {offers.map((offer) => {
          const conditionLabel = getOfferConditionLabel(offer);
          const showSundayNotification = offer.isSundayOffer && !isSunday;

          return (
            <div
              key={offer.id}
              className={`relative overflow-hidden rounded-[2rem] border border-white/10 bg-slate-950/40 p-5 shadow-2xl backdrop-blur-md flex flex-col justify-between transition-all ${
                !offer.enabled ? 'opacity-40 grayscale-[20%]' : ''
              }`}
            >
              <div>
                <div className="flex justify-between items-start mb-3">
                  <div className="flex flex-col gap-1 pr-2">
                    <h4 className="text-lg font-display font-black text-white leading-tight">{offer.offerTitle}</h4>
                    {offer.isSundayOffer && (
                      <span className="inline-flex w-fit items-center rounded-full bg-orange-950/60 border border-orange-500/30 px-2 py-0.5 text-[8px] font-black uppercase tracking-widest text-orange-400">
                        📅 Sunday automated
                      </span>
                    )}
                  </div>
                  
                  <div className="flex space-x-2">
                    <button
                      onClick={() => handleToggleEnabled(offer)}
                      className={`px-3 py-1.5 rounded-xl text-[9px] font-black uppercase tracking-widest border transition-all cursor-pointer ${
                        offer.enabled
                          ? 'bg-emerald-600/10 border-emerald-500/30 text-emerald-400 hover:bg-emerald-600/25'
                          : 'bg-red-650/10 border-red-500/30 text-red-400 hover:bg-red-650/25'
                      }`}
                    >
                      {offer.enabled ? 'Enabled' : 'Disabled'}
                    </button>
                    {session.role !== 'staff' && (
                      <button
                        onClick={() => handleDelete(offer.id)}
                        className="p-1.5 rounded-xl border border-white/10 hover:border-red-500/30 text-slate-400 hover:text-red-400 transition-all cursor-pointer"
                        title="Delete Offer"
                      >
                        🗑️
                      </button>
                    )}
                  </div>
                </div>

                <p className="text-xs text-slate-300 font-semibold leading-relaxed mb-4">{offer.displayText}</p>
                
                <div className="grid gap-3 sm:grid-cols-[80px,1fr] bg-slate-900/40 border border-white/5 rounded-2xl p-3">
                  <img
                    src={offer.image}
                    alt={offer.offerTitle}
                    className="h-16 w-full sm:w-20 rounded-xl object-cover shadow-inner"
                  />
                  <div className="text-[10px] space-y-1.5 text-slate-400 font-semibold self-center">
                    <div>
                      <span className="text-slate-500">Condition:</span>{' '}
                      <span className="text-yellow-400 font-black">{conditionLabel}</span>
                    </div>
                    {offer.additionalItem && (
                      <div className="flex items-center space-x-1.5">
                        <span className="text-slate-500">Freebie:</span>{' '}
                        <span className="text-emerald-400 font-black">{offer.additionalItem}</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {showSundayNotification && (
                <div className="mt-3 text-center text-[9px] font-bold text-slate-500 uppercase tracking-wider">
                  ⏸️ Inactive: Automatically triggers on Sundays
                </div>
              )}
            </div>
          );
        })}

        {offers.length === 0 && (
          <div className="col-span-2 rounded-[2rem] border border-dashed border-white/10 bg-slate-950/20 py-16 text-center text-slate-500 font-bold text-sm">
            No active promotional campaigns configured.
          </div>
        )}
      </div>
    </section>
  );
};
